address:
  street: 825 N 2nd St
  state: Philadelphia, PA 12123
  phone: (215) 425-2450
baseurl: ""
description: >
  Exit Skateshop
email: shop@exitphiladelphia.com
markdown: kramdown
social:
  twitter: exitphiladelphia
  instagram:  exitphiladelphia
  facebook: ExitSkateshop
title: Exit Philadelphia
url: "http://exitphiladelphia.com"
