address:
  street: "825 N 2ND ST"
  state: "PHILADELPHIA, PA 19123"
  phone: "(215) 425-2450"
baseurl: ""
collections:
  events:
    output: true
description: >
  Exit Skateshop
email: "SHOP@EXITPHILADELPHIA.COM"
social:
  twitter: "exitphiladelphia"
  instagram: "exitphiladelphia"
  facebook: "ExitSkateshop"
store: "https://exitphiladelphia.bigcartel.com"
title: "Exit Philadelphia"
url: "http://exitphiladelphia.com"
